### PR TITLE
fix: sparkSparkEmrServerlessJob doesn’t provide the removal_policy parameter

### PR DESCRIPTION
**Pull request by alexvt-amz**
## Description of changes:

Added removalPolicy property to sparkSparkEmrServerlessJob
Updated unit tests.

**Checklist**

 

* [X] Update tests
* [ ] Update docs
* [X] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

### CODE REVIEW

**Comment by lmouhib** [comment]
solves #183

**Comment by vgkowski** [comment]
you also need to set the global removal policy int he e2e stack
`stack.node.setContext('@aws-data-solutions-framework/removeDataOnDestroy', true);`

**Comment by alexvt-amz** [comment]
> can you add removal policy DESTROY in e2e test?

Done

**Comment by alexvt-amz** [comment]
> you also need to set the global removal policy int he e2e stack `stack.node.setContext('@aws-data-solutions-framework/removeDataOnDestroy', true);`

**Review by vgkowski — APPROVED** [review]

**Pull request merged**
